"""
This type stub file was generated by pyright.
"""

class Request:
    def __init__(self, profile_url, max_retries=..., proxy=...) -> None:
        ...
    
    def __get_guest_token__(self, profile_url, max_retries=...): # -> Any | None:
        ...
    
    def verify_user(self, data): # -> Any | Literal[0]:
        ...
    
    def get_tweets(self, data, replies=...): # -> Response:
        ...
    
    def get_trends(self): # -> Response:
        ...
    
    def perform_search(self, keyword, cursor, filter_): # -> Response:
        ...
    
    def get_tweet_detail(self, tweetId): # -> Response:
        ...
    


