"""
This type stub file was generated by pyright.
"""

def get_headers(typed=...) -> dict:
    ...

def searchFilters(filter_): # -> LiteralString | Literal['https://twitter.com/i/api/2/search/adaptive.json?i…']:
    ...

