version: "3.4"

volumes:
  app_db_data:
    driver: local
  
services:
  app_db:
    image: postgres:14.5
    ports:
      - 5438:5432
    expose:
      - 5438
    volumes:
      - app_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dev_app
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
  test-wrap:
    build:
      dockerfile: ./apps/test-wrap/Dockerfile
    environment:
      - DATABASE_URL=postgresql://dev_user:dev_password@app_db:5438/dev_app?schema=public
    ports:
      - 8000:3000