version: "3.4"

volumes:
  app_db_data:
    driver: local
  minio_data:
    driver: local
  # redis_data:
  #   driver: local
  
services:
  app_db:
    image: postgres:14.5
    ports:
      - 5438:5432
    expose:
      - 5438
    volumes:
      - app_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dev_app
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
  test-wrap:
    build:
      dockerfile: ./apps/test-wrap/Dockerfile
    environment:
      - DATABASE_URL=postgresql://dev_user:dev_password@app_db:5438/dev_app?schema=public
    ports:
      - 8000:3000
  minio:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /minio_data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_HTTP_TRACE: /dev/stdout
    hostname: minio
    # common healthcheck settings found online
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 12000:9000
      - 12001:9001
    volumes:
      - minio_data:/minio_data



  # not used anymore really
  # redis:
  #   image: redis:6.2.3-alpine
  #   hostname: redis
  #   command: ["redis-server", "--appendonly", "yes", "--port", "6380"]
  #   expose:
  #     - 6380
  #   ports:
  #     - "6380:6380"
  #   volumes:
  #     - redis_data:/data