"""
This type stub file was generated by pyright.
"""

from . import deprecated

class Search(dict):
    def __init__(self, keyword, http, pages=..., filter_=..., wait_time=..., cursor=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def get_next_page(self): # -> list[Unknown] | None:
        ...
    
    def to_xlsx(self, filename=...): # -> AttributeError | Excel:
        ...
    
    @deprecated
    def to_dict(self): # -> list[Unknown]:
        ...
    
    def __getitem__(self, index):
        ...
    
    def __iter__(self): # -> Generator[Unknown, None, None]:
        ...
    


