"""
This type stub file was generated by pyright.
"""

WORKBOOK_HEADERS = ...
def deprecated(func): # -> (*args: Unknown, **kwargs: Unknown) -> Unknown:
    """

    This is a decorator which can be used to mark functions
    as deprecated. It will result in a warning being emitted
    when the function is used.

    """
    ...

def get_graph_ql_query(typed, user, pages=...) -> str:
    """

    :param typed: internal script query type
    :param user: username or user_id
    :param pages: cursor of next page
    :return: string on graphql query object
    """
    ...

def bar_progress(current, total, width=...): # -> None:
    ...

class Excel:
    def __init__(self, tweets, user, filename=...) -> None:
        ...
    


class Tweet(dict):
    def __init__(self, raw_response, raw_tweet, http, get_threads=..., is_legacy_user=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __iter__(self): # -> Generator[Unknown, None, None]:
        ...
    
    @deprecated
    def to_dict(self): # -> dict[str, Unknown | UserLegacy | User | bool | Tweet | str | Card | Place | list[Media] | list[ShortUser] | list[Unknown] | None]:
        ...
    


class Media(dict):
    def __init__(self, media_dict) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def download(self, filename_, show_progress=...): # -> str | None:
        ...
    
    @deprecated
    def to_dict(self): # -> Unknown:
        ...
    


class Stream(dict):
    def __init__(self, videoDict, length, ratio) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def download(self, filename_=..., show_progress=...): # -> str | None:
        ...
    


class ShortUser(dict):
    def __init__(self, user_dict) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def to_dict(self): # -> Unknown:
        ...
    


class User(dict):
    def __init__(self, user_dict, type_=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @deprecated
    def to_dict(self): # -> Unknown:
        ...
    


class Trends:
    def __init__(self, trends_dict) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def to_dict(self): # -> Unknown:
        ...
    


class UserLegacy(dict):
    def __init__(self, user_dict) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def to_dict(self): # -> Unknown:
        ...
    


class Card(dict):
    def __init__(self, card_dict) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class Choice(dict):
    def __init__(self, _dict) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class Place(dict):
    def __init__(self, place_dict) -> None:
        ...
    
    def parse_coordinates(self): # -> list[Coordinates]:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class Coordinates(dict):
    def __init__(self, latitude, longitude) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


