name: "prisma-migrate"
description: "Prisma DB migration"
runs:
  using: "composite"
  steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: migrate prisma changes
      shell: bash
      run: yarn dp:pushprod
