export const abbreviationDictionary = {
  afk: "away from keyboard",
  asap: "as soon as possible",
  btw: "by the way",
  brb: "be right back",
  bc: "because",
  cya: "see you",
  f2f: "face to face",
  fyi: "for your information",
  g2g: "got to go",
  gg: "good game",
  gl: "good luck",
  gtg: "got to go",
  idk: "I don't know",
  imo: "in my opinion",
  iow: "in other words",
  irl: "in real life",
  jk: "just kidding",
  l8r: "later",
  nvm: "never mind",
  rofl: "rolling on the floor laughing",
  tbh: "to be honest",
  ty: "thank you",
  wtf: "what the heck",
};
