version: "3.4"

volumes:
  redis_data:
    driver: local
  minio_data:
    driver: local
services:
  api:
    image: registry.yungstentech.com/cog-api:latest
    user: root
    ports:
      - "15000:3000"
    expose:
      - 15000
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - ../../.env
    environment:
      - ENVIRONMENT=development
  workers:
    image: registry.yungstentech.com/cog-workers:latest
    user: root
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - ../../.env
    environment:
      - ENVIRONMENT=development
  redis:
    image: redis:6.2.3-alpine
    hostname: redis
    command: ["redis-server", "--appendonly", "yes", "--port", "6380"]
    env_file:
      - ../../.env
    expose:
      - 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
  minio:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /minio_data
    env_file:
      - ../../.env
    hostname: minio
    # common healthcheck settings found online
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 12000:9000
      - 12001:9001
    volumes:
      - minio_data:/minio_data
