#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Change this to use a non-default directory for Vector data storage:
# data_dir = "/var/lib/vector"

[sources.main_stdin]
type = "stdin"

[transforms.extract_logs]
  type = "remap"
  inputs = ["main_stdin"]
  source = """
    .fileLine = to_int!(.fileLine)
    .date = parse_timestamp(.date, "%Y-%m-%dT%H:%M:%S%.3f%z") ?? now()
    service, err = get_env_var("COG_SERVICE_BUILD_NAME")
    .level = to_int!(.levelId)
  """

[transforms.add_fields]
  type = "remap"
  inputs = ["extract_logs"]
  source = '''
    if err != null {
      . = merge(., {
        "application": "cog",
        "service": "unknown"
      })
    } else {
        . |= {
        "application": "cog",
        "service": service
      }
    }
  '''

[sinks.vector_home]
type = "vector"
inputs = [ "add_fields" ]
address = "http://vector.yungstentech.com:9999"

# Vector's GraphQL API (disabled by default)
# Uncomment to try it out with the `vector top` command or
# in your browser at http://localhost:8686
#[api]
#enabled = true
#address = "127.0.0.1:8686"