-- AlterTable
ALTER TABLE "TwitterUser" ALTER COLUMN "created_on" DROP NOT NULL,
ALTER COLUMN "default_profile" DROP NOT NULL,
ALTER COLUMN "default_profile_image" DROP NOT NULL,
ALTER COLUMN "favourites_count" DROP NOT NULL,
ALTER COLUMN "friends_count" DROP NOT NULL,
ALTER COLUMN "has_custom_timelines" DROP NOT NULL,
ALTER COLUMN "is_translator" DROP NOT NULL,
ALTER COLUMN "listed_count" DROP NOT NULL,
ALTER COLUMN "location" DROP NOT NULL,
ALTER COLUMN "media_count" DROP NOT NULL,
ALTER COLUMN "possibly_sensitive" DROP NOT NULL,
ALTER COLUMN "profile_banner_url" DROP NOT NULL,
ALTER COLUMN "profile_image_url_https" DROP NOT NULL,
ALTER COLUMN "profile_interstitial_type" DROP NOT NULL,
ALTER COLUMN "profile_url" DROP NOT NULL,
ALTER COLUMN "protected" DROP NOT NULL,
ALTER COLUMN "rest_id" DROP NOT NULL,
ALTER COLUMN "statuses_count" DROP NOT NULL,
ALTER COLUMN "translator_type" DROP NOT NULL,
ALTER COLUMN "verified_type" DROP NOT NULL;
