name: production deploy of cog
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  Deploy:
    name: Production Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4

      - name: Build and push to registry.yungstentech.com
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/cog/api.Dockerfile
          push: true
          tags: registry.yungstentech.com/cog-api:latest

      - name: Build and push to registry.yungstentech.com
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/cog/workers.Dockerfile
          push: true
          tags: registry.yungstentech.com/cog-workers:latest

      - name: SSH into dedicated host docker run
        uses: appleboy/ssh-action@master
        env:
          DOT_ENV_FILE: ${{ secrets.DOT_ENV_FILE }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEDI_DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_HOST_SSH_KEY }}
          envs: DOT_ENV_FILE
          script: |
            rm -rf cog-deploy && mkdir cog-deploy && cd cog-deploy
            git clone git@github.com-cog:paulmikulskis/redditat.git
            echo "hydrating .env"
            cd redditat && echo "$DOT_ENV_FILE" > .env
            docker compose down -v
            docker image rm --force registry.yungstentech.com/cog-api:latest
            docker image rm --force registry.yungstentech.com/cog-workers:latest
            make cog-prod
